spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: hr
    password: happy
    driver-class-name: oracle.jdbc.driver.OracleDriver
  jpa:
    database: oracle
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
        format_sql: true
        user_sql_comments: true
logging:
    level: 
      org.hibernate.SQL: DEBUG
      org.hibernate.orm.jdbc.bind: TRACE 
